### ISSUE TITLE
Mod is currently not up to date.

### ISSUE THREAD

**Issue by NoviceCoder2000** [SomeTroglodyte/Aliens-have-crashed-on-Earth#4]
Mod is currently not up to date for the latest version of unciv as tile improvement is not compatible with current tilesets.

![Screenshot_20210707-150831_UnCiv](https://user-images.githubusercontent.com/83058051/125025907-1cfdd900-e0b6-11eb-8256-7332c09940b8.jpg)

**Comment by SomeTroglodyte** [comment]
I've seen that and not yet considered properly. Is the terrain feature actually named Hill and not Hills? Why, indeed it is.
